@CatalogAPI_HostAddress = https://localhost:5050

# POST /api/products
POST {{CatalogAPI_HostAddress}}/products
Content-Type: application/json

{
    "Name": "Product A",
    "Category": ["a","b"],
    "Description": "Description Product",
    "ImageFile": "Image Product",
    "Price": 123
}

###
# GET /api/products
GET {{CatalogAPI_HostAddress}}/products


###
# GET /api/products/{id}
GET {{CatalogAPI_HostAddress}}/products/1

###
# GET /api/products/category/{category}
GET {{CatalogAPI_HostAddress}}/products/category/a

### Delete
# POST /api/products/{id}
POST {{CatalogAPI_HostAddress}}/products/id

### Update
# POST /api/products/{id}
POST {{CatalogAPI_HostAddress}}/products
Content-Type: application/json

{
    "Id": 1,
    "Name": "Product B",
    "Category": ["a","b"],
    "Description": "Description Product",
    "ImageFile": "Image Product",
    "Price": 234
}