version: '3.4'

services:
  catalogdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
